/* dash-spv-ffi C bindings - Auto-generated by cbindgen */

#ifndef DASH_SPV_FFI_H
#define DASH_SPV_FFI_H

/* Generated with cbindgen:0.29.2 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace dash_spv_ffi {
#endif  // __cplusplus

/**
 * SyncState exposed by the FFI as FFISyncState.
 */
typedef enum FFISyncState {
  WaitForEvents = 0,
  WaitingForConnections = 1,
  Syncing = 2,
  Synced = 3,
  Error = 4,
} FFISyncState;

/**
 * Identifies which sync manager generated an event.
 */
typedef enum FFIManagerId {
  Headers = 0,
  FilterHeaders = 1,
  Filters = 2,
  Blocks = 3,
  Masternodes = 4,
  ChainLocks = 5,
  InstantSend = 6,
} FFIManagerId;

typedef enum FFIMempoolStrategy {
  FetchAll = 0,
  BloomFilter = 1,
} FFIMempoolStrategy;

typedef struct FFIDashSpvClient FFIDashSpvClient;

typedef struct FFIClientConfig {
  void *inner;
  uint32_t worker_threads;

} FFIClientConfig;

/**
 * Progress for block headers synchronization.
 */
typedef struct FFIBlockHeadersProgress {
  enum FFISyncState state;
  uint32_t tip_height;
  uint32_t target_height;
  uint32_t processed;
  uint32_t buffered;
  double percentage;
  uint64_t last_activity;
} FFIBlockHeadersProgress;

/**
 * Progress for filter headers synchronization.
 */
typedef struct FFIFilterHeadersProgress {
  enum FFISyncState state;
  uint32_t current_height;
  uint32_t target_height;
  uint32_t block_header_tip_height;
  uint32_t processed;
  double percentage;
  uint64_t last_activity;
} FFIFilterHeadersProgress;

/**
 * Progress for compact block filters synchronization.
 */
typedef struct FFIFiltersProgress {
  enum FFISyncState state;
  uint32_t committed_height;
  uint32_t stored_height;
  uint32_t target_height;
  uint32_t filter_header_tip_height;
  uint32_t downloaded;
  uint32_t processed;
  uint32_t matched;
  double percentage;
  uint64_t last_activity;
} FFIFiltersProgress;

/**
 * Progress for full block synchronization.
 */
typedef struct FFIBlocksProgress {
  enum FFISyncState state;
  uint32_t last_processed;
  uint32_t requested;
  uint32_t from_storage;
  uint32_t downloaded;
  uint32_t processed;
  uint32_t relevant;
  uint32_t transactions;
  uint64_t last_activity;
} FFIBlocksProgress;

/**
 * Progress for masternode list synchronization.
 */
typedef struct FFIMasternodesProgress {
  enum FFISyncState state;
  uint32_t current_height;
  uint32_t target_height;
  uint32_t block_header_tip_height;
  uint32_t diffs_processed;
  uint64_t last_activity;
} FFIMasternodesProgress;

/**
 * Progress for ChainLock synchronization.
 */
typedef struct FFIChainLockProgress {
  enum FFISyncState state;
  uint32_t best_validated_height;
  uint32_t valid;
  uint32_t invalid;
  uint64_t last_activity;
} FFIChainLockProgress;

/**
 * Progress for InstantSend synchronization.
 */
typedef struct FFIInstantSendProgress {
  enum FFISyncState state;
  uint32_t pending;
  uint32_t valid;
  uint32_t invalid;
  uint64_t last_activity;
} FFIInstantSendProgress;

/**
 * Aggregate progress for all sync managers.
 * Provides a complete view of the parallel sync system's state.
 */
typedef struct FFISyncProgress {
  enum FFISyncState state;
  double percentage;
  bool is_synced;
  /**
   * Per-manager progress (null if manager not started).
   */
  struct FFIBlockHeadersProgress *headers;
  struct FFIFilterHeadersProgress *filter_headers;
  struct FFIFiltersProgress *filters;
  struct FFIBlocksProgress *blocks;
  struct FFIMasternodesProgress *masternodes;
  struct FFIChainLockProgress *chainlocks;
  struct FFIInstantSendProgress *instantsend;
} FFISyncProgress;

/**
 * Opaque handle to the wallet manager owned by the SPV client.
 *
 * This is intentionally zero-sized so it can be used purely as an FFI handle
 * while still allowing Rust to cast to the underlying key-wallet manager
 * implementation when necessary.
 */
typedef struct FFIWalletManager {
  uint8_t _private[0];
} FFIWalletManager;

/**
 * Callback for SyncEvent::SyncStart
 */
typedef void (*OnSyncStartCallback)(enum FFIManagerId manager_id, void *user_data);

/**
 * Callback for SyncEvent::BlockHeadersStored
 */
typedef void (*OnBlockHeadersStoredCallback)(uint32_t tip_height, void *user_data);

/**
 * Callback for SyncEvent::BlockHeaderSyncComplete
 */
typedef void (*OnBlockHeaderSyncCompleteCallback)(uint32_t tip_height, void *user_data);

/**
 * Callback for SyncEvent::FilterHeadersStored
 */
typedef void (*OnFilterHeadersStoredCallback)(uint32_t start_height,
                                              uint32_t end_height,
                                              uint32_t tip_height,
                                              void *user_data);

/**
 * Callback for SyncEvent::FilterHeadersSyncComplete
 */
typedef void (*OnFilterHeadersSyncCompleteCallback)(uint32_t tip_height, void *user_data);

/**
 * Callback for SyncEvent::FiltersStored
 */
typedef void (*OnFiltersStoredCallback)(uint32_t start_height, uint32_t end_height, void *user_data);

/**
 * Callback for SyncEvent::FiltersSyncComplete
 */
typedef void (*OnFiltersSyncCompleteCallback)(uint32_t tip_height, void *user_data);

/**
 * A block that needs to be downloaded (height + hash).
 */
typedef struct FFIBlockNeeded {
  /**
   * Block height
   */
  uint32_t height;
  /**
   * Block hash (32 bytes)
   */
  uint8_t hash[32];
} FFIBlockNeeded;

/**
 * Callback for SyncEvent::BlocksNeeded
 *
 * The `blocks` pointer points to an array of `FFIBlockNeeded` structs.
 * The pointer is borrowed and only valid for the duration of the callback.
 * Callers must memcpy/duplicate any data they need to retain after the
 * callback returns.
 */
typedef void (*OnBlocksNeededCallback)(const struct FFIBlockNeeded *blocks,
                                       uint32_t count,
                                       void *user_data);

/**
 * Callback for SyncEvent::BlockProcessed
 *
 * The `hash` pointer is borrowed and only valid for the duration of the
 * callback. Callers must memcpy/duplicate it to retain the value after
 * the callback returns.
 */
typedef void (*OnBlockProcessedCallback)(uint32_t height,
                                         const uint8_t (*hash)[32],
                                         uint32_t new_address_count,
                                         void *user_data);

/**
 * Callback for SyncEvent::MasternodeStateUpdated
 */
typedef void (*OnMasternodeStateUpdatedCallback)(uint32_t height, void *user_data);

/**
 * Callback for SyncEvent::ChainLockReceived
 *
 * The `hash` and `signature` pointers are borrowed and only valid for the
 * duration of the callback. Callers must memcpy/duplicate them to retain
 * the values after the callback returns.
 */
typedef void (*OnChainLockReceivedCallback)(uint32_t height,
                                            const uint8_t (*hash)[32],
                                            const uint8_t (*signature)[96],
                                            bool validated,
                                            void *user_data);

/**
 * Callback for SyncEvent::InstantLockReceived
 *
 * The `txid` pointer is borrowed and only valid for the duration of the callback.
 * The `instantlock_data` pointer points to the consensus-serialized InstantLock
 * bytes and is only valid for the duration of the callback.
 * Callers must memcpy/duplicate any data they need to retain.
 */
typedef void (*OnInstantLockReceivedCallback)(const uint8_t (*txid)[32],
                                              const uint8_t *instantlock_data,
                                              uintptr_t instantlock_len,
                                              bool validated,
                                              void *user_data);

/**
 * Callback for SyncEvent::ManagerError
 *
 * The `error` string pointer is borrowed and only valid for the duration
 * of the callback. Callers must copy the string if they need to retain it
 * after the callback returns.
 */
typedef void (*OnManagerErrorCallback)(enum FFIManagerId manager_id,
                                       const char *error,
                                       void *user_data);

/**
 * Callback for SyncEvent::SyncComplete
 */
typedef void (*OnSyncCompleteCallback)(uint32_t header_tip, uint32_t cycle, void *user_data);

/**
 * Sync event callbacks - one callback per SyncEvent variant.
 *
 * Set only the callbacks you're interested in; unset callbacks will be ignored.
 *
 * All pointer parameters passed to callbacks (strings, hashes, arrays) are
 * borrowed and only valid for the duration of the callback invocation.
 * Callers must memcpy/duplicate any data they need to retain.
 */
typedef struct FFISyncEventCallbacks {
  OnSyncStartCallback on_sync_start;
  OnBlockHeadersStoredCallback on_block_headers_stored;
  OnBlockHeaderSyncCompleteCallback on_block_header_sync_complete;
  OnFilterHeadersStoredCallback on_filter_headers_stored;
  OnFilterHeadersSyncCompleteCallback on_filter_headers_sync_complete;
  OnFiltersStoredCallback on_filters_stored;
  OnFiltersSyncCompleteCallback on_filters_sync_complete;
  OnBlocksNeededCallback on_blocks_needed;
  OnBlockProcessedCallback on_block_processed;
  OnMasternodeStateUpdatedCallback on_masternode_state_updated;
  OnChainLockReceivedCallback on_chainlock_received;
  OnInstantLockReceivedCallback on_instantlock_received;
  OnManagerErrorCallback on_manager_error;
  OnSyncCompleteCallback on_sync_complete;
  void *user_data;
} FFISyncEventCallbacks;

/**
 * Callback for NetworkEvent::PeerConnected
 *
 * The `address` string pointer is borrowed and only valid for the duration
 * of the callback. Callers must copy the string if they need to retain it
 * after the callback returns.
 */
typedef void (*OnPeerConnectedCallback)(const char *address, void *user_data);

/**
 * Callback for NetworkEvent::PeerDisconnected
 *
 * The `address` string pointer is borrowed and only valid for the duration
 * of the callback. Callers must copy the string if they need to retain it
 * after the callback returns.
 */
typedef void (*OnPeerDisconnectedCallback)(const char *address, void *user_data);

/**
 * Callback for NetworkEvent::PeersUpdated
 */
typedef void (*OnPeersUpdatedCallback)(uint32_t connected_count,
                                       uint32_t best_height,
                                       void *user_data);

/**
 * Network event callbacks - one callback per NetworkEvent variant.
 *
 * Set only the callbacks you're interested in; unset callbacks will be ignored.
 *
 * All pointer parameters passed to callbacks (strings, addresses) are
 * borrowed and only valid for the duration of the callback invocation.
 * Callers must copy any data they need to retain.
 */
typedef struct FFINetworkEventCallbacks {
  OnPeerConnectedCallback on_peer_connected;
  OnPeerDisconnectedCallback on_peer_disconnected;
  OnPeersUpdatedCallback on_peers_updated;
  void *user_data;
} FFINetworkEventCallbacks;

/**
 * Callback for WalletEvent::TransactionReceived
 *
 * The `wallet_id`, `addresses` string pointers and the `txid` hash pointer
 * are borrowed and only valid for the duration of the callback. Callers must
 * copy any data they need to retain after the callback returns.
 */
typedef void (*OnTransactionReceivedCallback)(const char *wallet_id,
                                              uint32_t account_index,
                                              const uint8_t (*txid)[32],
                                              int64_t amount,
                                              const char *addresses,
                                              void *user_data);

/**
 * Callback for WalletEvent::BalanceUpdated
 *
 * The `wallet_id` string pointer is borrowed and only valid for the duration
 * of the callback. Callers must copy the string if they need to retain it
 * after the callback returns.
 */
typedef void (*OnBalanceUpdatedCallback)(const char *wallet_id,
                                         uint64_t spendable,
                                         uint64_t unconfirmed,
                                         uint64_t immature,
                                         uint64_t locked,
                                         void *user_data);

/**
 * Wallet event callbacks - one callback per WalletEvent variant.
 *
 * Set only the callbacks you're interested in; unset callbacks will be ignored.
 *
 * All pointer parameters passed to callbacks (wallet IDs, txids, addresses)
 * are borrowed and only valid for the duration of the callback invocation.
 * Callers must copy any data they need to retain.
 */
typedef struct FFIWalletEventCallbacks {
  OnTransactionReceivedCallback on_transaction_received;
  OnBalanceUpdatedCallback on_balance_updated;
  void *user_data;
} FFIWalletEventCallbacks;

/**
 * Callback for sync progress updates.
 *
 * Called whenever the sync progress changes. The progress pointer is only
 * valid for the duration of the callback. The caller must NOT free the
 * progress pointer - it will be freed automatically after the callback returns.
 */
typedef void (*OnProgressUpdateCallback)(const struct FFISyncProgress *progress, void *user_data);

/**
 * Progress callback configuration.
 */
typedef struct FFIProgressCallback {
  /**
   * Callback function for progress updates.
   */
  OnProgressUpdateCallback on_progress;
  /**
   * User data passed to the callback.
   */
  void *user_data;
} FFIProgressCallback;

/**
 * FFIResult type for error handling
 */
typedef struct FFIResult {
  int32_t error_code;
  const char *error_message;
} FFIResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new SPV client and return an opaque pointer.
 *
 * # Safety
 * - `config` must be a valid, non-null pointer for the duration of the call.
 * - The returned pointer must be freed with `dash_spv_ffi_client_destroy`.
 */
 struct FFIDashSpvClient *dash_spv_ffi_client_new(const struct FFIClientConfig *config) ;

/**
 * Update the running client's configuration.
 *
 * # Safety
 * - `client` must be a valid pointer to an `FFIDashSpvClient`.
 * - `config` must be a valid pointer to an `FFIClientConfig`.
 * - The network in `config` must match the client's network; changing networks at runtime is not supported.
 */

int32_t dash_spv_ffi_client_update_config(struct FFIDashSpvClient *client,
                                          const struct FFIClientConfig *config)
;

/**
 * Stop the SPV client.
 *
 * # Safety
 * - `client` must be a valid, non-null pointer to a created client.
 */
 int32_t dash_spv_ffi_client_stop(struct FFIDashSpvClient *client) ;

/**
 * Start the SPV client and begin syncing in the background.
 *
 * Subscribes to events, spawns monitoring threads, then spawns a background
 * thread that calls `run()` (which handles start + sync loop + stop internally).
 * Returns immediately after spawning.
 *
 * Use event callbacks (set via `set_sync_event_callbacks`,
 * `set_network_event_callbacks`, `set_wallet_event_callbacks`) to receive
 * notifications. Configure callbacks before calling `run()`.
 *
 * # Safety
 * - `client` must be a valid, non-null pointer to a created client.
 *
 * # Returns
 * 0 on success, error code on failure.
 */
 int32_t dash_spv_ffi_client_run(struct FFIDashSpvClient *client) ;

/**
 * Get the current sync progress snapshot.
 *
 * # Safety
 * - `client` must be a valid, non-null pointer.
 */
 struct FFISyncProgress *dash_spv_ffi_client_get_sync_progress(struct FFIDashSpvClient *client) ;

/**
 * Get the current manager-based sync progress.
 *
 * Returns the new parallel sync system's progress with per-manager details.
 * Use `dash_spv_ffi_manager_sync_progress_destroy` to free the returned struct.
 *
 * # Safety
 * - `client` must be a valid, non-null pointer.
 */

struct FFISyncProgress *dash_spv_ffi_client_get_manager_sync_progress(struct FFIDashSpvClient *client)
;

/**
 * Clear all persisted SPV storage (headers, filters, metadata, sync state).
 *
 * # Safety
 * - `client` must be a valid, non-null pointer.
 */
 int32_t dash_spv_ffi_client_clear_storage(struct FFIDashSpvClient *client) ;

/**
 * Broadcasts a transaction to the Dash network via connected peers.
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer to an initialized FFIDashSpvClient
 * - `tx_bytes` must be a valid, non-null pointer to the transaction data
 * - `length` must be the length of the transaction data in bytes
 */

int32_t dash_spv_ffi_client_broadcast_transaction(struct FFIDashSpvClient *client,
                                                  const uint8_t *tx_bytes,
                                                  uintptr_t length)
;

/**
 * Destroy the client and free associated resources.
 *
 * # Safety
 * - `client` must be either null or a pointer obtained from `dash_spv_ffi_client_new`.
 */
 void dash_spv_ffi_client_destroy(struct FFIDashSpvClient *client) ;

/**
 * Destroy a `FFISyncProgress` object returned by this crate.
 *
 * # Safety
 * - `progress` must be a pointer returned from this crate, or null.
 */
 void dash_spv_ffi_sync_progress_destroy(struct FFISyncProgress *progress) ;

/**
 * Get the wallet manager from the SPV client
 *
 * Returns a pointer to an `FFIWalletManager` wrapper that clones the underlying
 * `Arc<RwLock<WalletManager>>`. This allows direct interaction with the wallet
 * manager without going back through the client for each call.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - The client pointer is valid
 * - The returned pointer is released exactly once using
 *   `dash_spv_ffi_wallet_manager_free`
 *
 * # Returns
 *
 * A pointer to the wallet manager wrapper, or NULL if the client is not initialized.
 */
 struct FFIWalletManager *dash_spv_ffi_client_get_wallet_manager(struct FFIDashSpvClient *client) ;

/**
 * Release a wallet manager obtained from `dash_spv_ffi_client_get_wallet_manager`.
 *
 * This simply forwards to `wallet_manager_free` in key-wallet-ffi so that
 * lifetime management is consistent between direct key-wallet usage and the
 * SPV client pathway.
 *
 * # Safety
 * - `manager` must either be null or a pointer previously returned by
 *   `dash_spv_ffi_client_get_wallet_manager`.
 */
 void dash_spv_ffi_wallet_manager_free(struct FFIWalletManager *manager) ;

/**
 * Set sync event callbacks for push-based event notifications.
 *
 * The monitoring task is spawned when `dash_spv_ffi_client_run` is called.
 * Call this before calling run().
 *
 * # Safety
 * - `client` must be a valid, non-null pointer to an `FFIDashSpvClient`.
 * - The `callbacks` struct and its `user_data` must remain valid until callbacks are cleared.
 * - Callbacks must be thread-safe as they may be called from a background task.
 */

int32_t dash_spv_ffi_client_set_sync_event_callbacks(struct FFIDashSpvClient *client,
                                                     struct FFISyncEventCallbacks callbacks)
;

/**
 * Clear sync event callbacks.
 *
 * # Safety
 * - `client` must be a valid, non-null pointer to an `FFIDashSpvClient`.
 */
 int32_t dash_spv_ffi_client_clear_sync_event_callbacks(struct FFIDashSpvClient *client) ;

/**
 * Set network event callbacks for push-based event notifications.
 *
 * The monitoring task is spawned when `dash_spv_ffi_client_run` is called.
 * Call this before calling run().
 *
 * # Safety
 * - `client` must be a valid, non-null pointer to an `FFIDashSpvClient`.
 * - The `callbacks` struct and its `user_data` must remain valid until callbacks are cleared.
 * - Callbacks must be thread-safe as they may be called from a background task.
 */

int32_t dash_spv_ffi_client_set_network_event_callbacks(struct FFIDashSpvClient *client,
                                                        struct FFINetworkEventCallbacks callbacks)
;

/**
 * Clear network event callbacks.
 *
 * # Safety
 * - `client` must be a valid, non-null pointer to an `FFIDashSpvClient`.
 */
 int32_t dash_spv_ffi_client_clear_network_event_callbacks(struct FFIDashSpvClient *client) ;

/**
 * Set wallet event callbacks for push-based event notifications.
 *
 * The monitoring task is spawned when `dash_spv_ffi_client_run` is called.
 * Call this before calling run().
 *
 * # Safety
 * - `client` must be a valid, non-null pointer to an `FFIDashSpvClient`.
 * - The `callbacks` struct and its `user_data` must remain valid until callbacks are cleared.
 * - Callbacks must be thread-safe as they may be called from a background task.
 */

int32_t dash_spv_ffi_client_set_wallet_event_callbacks(struct FFIDashSpvClient *client,
                                                       struct FFIWalletEventCallbacks callbacks)
;

/**
 * Clear wallet event callbacks.
 *
 * # Safety
 * - `client` must be a valid, non-null pointer to an `FFIDashSpvClient`.
 */
 int32_t dash_spv_ffi_client_clear_wallet_event_callbacks(struct FFIDashSpvClient *client) ;

/**
 * Set progress callback for sync progress updates.
 *
 * The monitoring task is spawned when `dash_spv_ffi_client_run` is called.
 * Call this before calling run().
 *
 * # Safety
 * - `client` must be a valid, non-null pointer to an `FFIDashSpvClient`.
 * - The `callback` struct and its `user_data` must remain valid until the callback is cleared.
 * - The callback must be thread-safe as it may be called from a background task.
 */

int32_t dash_spv_ffi_client_set_progress_callback(struct FFIDashSpvClient *client,
                                                  struct FFIProgressCallback callback)
;

/**
 * Clear progress callback.
 *
 * # Safety
 * - `client` must be a valid, non-null pointer to an `FFIDashSpvClient`.
 */
 int32_t dash_spv_ffi_client_clear_progress_callback(struct FFIDashSpvClient *client) ;

 struct FFIClientConfig *dash_spv_ffi_config_new(FFINetwork network) ;

 struct FFIClientConfig *dash_spv_ffi_config_mainnet(void) ;

 struct FFIClientConfig *dash_spv_ffi_config_testnet(void) ;

/**
 * Sets the data directory for storing blockchain data
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig created by dash_spv_ffi_config_new/mainnet/testnet
 * - `path` must be a valid null-terminated C string
 * - The caller must ensure the config pointer remains valid for the duration of this call
 */

int32_t dash_spv_ffi_config_set_data_dir(struct FFIClientConfig *config,
                                         const char *path)
;

/**
 * Adds a peer address to the configuration
 *
 * Accepts socket addresses with or without port. When no port is specified,
 * the default P2P port for the configured network is used.
 *
 * Supported formats:
 * - IP with port: `192.168.1.1:9999`, `[::1]:19999`
 * - IP without port: `127.0.0.1`, `2001:db8::1`
 * - Hostname with port: `node.example.com:9999`
 * - Hostname without port: `node.example.com`
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig created by dash_spv_ffi_config_new/mainnet/testnet
 * - `addr` must be a valid null-terminated C string containing a socket address or IP-only string
 * - The caller must ensure both pointers remain valid for the duration of this call
 */

int32_t dash_spv_ffi_config_add_peer(struct FFIClientConfig *config,
                                     const char *addr)
;

/**
 * Sets the user agent string to advertise in the P2P handshake
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig created by dash_spv_ffi_config_new/mainnet/testnet
 * - `user_agent` must be a valid null-terminated C string
 * - The caller must ensure both pointers remain valid for the duration of this call
 */

int32_t dash_spv_ffi_config_set_user_agent(struct FFIClientConfig *config,
                                           const char *user_agent)
;

/**
 * Restrict connections strictly to configured peers (disable DNS discovery and peer store)
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig created by dash_spv_ffi_config_new/mainnet/testnet
 */

int32_t dash_spv_ffi_config_set_restrict_to_configured_peers(struct FFIClientConfig *config,
                                                             bool restrict_peers)
;

/**
 * Enables or disables masternode synchronization
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig created by dash_spv_ffi_config_new/mainnet/testnet
 * - The caller must ensure the config pointer remains valid for the duration of this call
 */

int32_t dash_spv_ffi_config_set_masternode_sync_enabled(struct FFIClientConfig *config,
                                                        bool enable)
;

/**
 * Gets the network type from the configuration
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig or null
 * - If null, returns FFINetwork::Dash as default
 */
 FFINetwork dash_spv_ffi_config_get_network(const struct FFIClientConfig *config) ;

/**
 * Destroys an FFIClientConfig and frees its memory
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig created by dash_spv_ffi_config_new/mainnet/testnet, or null
 * - After calling this function, the config pointer becomes invalid and must not be used
 * - This function should only be called once per config instance
 */

void dash_spv_ffi_config_destroy(struct FFIClientConfig *config)
;

/**
 * Enables or disables mempool tracking
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig created by dash_spv_ffi_config_new/mainnet/testnet
 * - The caller must ensure the config pointer remains valid for the duration of this call
 */

int32_t dash_spv_ffi_config_set_mempool_tracking(struct FFIClientConfig *config,
                                                 bool enable)
;

/**
 * Sets the mempool synchronization strategy
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig created by dash_spv_ffi_config_new/mainnet/testnet
 * - The caller must ensure the config pointer remains valid for the duration of this call
 */

int32_t dash_spv_ffi_config_set_mempool_strategy(struct FFIClientConfig *config,
                                                 enum FFIMempoolStrategy strategy)
;

/**
 * Sets whether to fetch full mempool transaction data
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig created by dash_spv_ffi_config_new/mainnet/testnet
 * - The caller must ensure the config pointer remains valid for the duration of this call
 */

int32_t dash_spv_ffi_config_set_fetch_mempool_transactions(struct FFIClientConfig *config,
                                                           bool fetch)
;

/**
 * Sets whether to persist mempool state to disk
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig created by dash_spv_ffi_config_new/mainnet/testnet
 * - The caller must ensure the config pointer remains valid for the duration of this call
 */

int32_t dash_spv_ffi_config_set_persist_mempool(struct FFIClientConfig *config,
                                                bool persist)
;

/**
 * Sets the starting block height for synchronization
 *
 * # Safety
 * - `config` must be a valid pointer to an FFIClientConfig created by dash_spv_ffi_config_new/mainnet/testnet
 * - The caller must ensure the config pointer remains valid for the duration of this call
 */

int32_t dash_spv_ffi_config_set_start_from_height(struct FFIClientConfig *config,
                                                  uint32_t height)
;

 const char *dash_spv_ffi_get_last_error(void) ;

/**
 * Gets a quorum public key from the Core chain
 *
 * # Safety
 *
 * This function is unsafe because:
 * - The caller must ensure all pointers are valid
 * - quorum_hash must point to a 32-byte array
 * - out_pubkey must point to a buffer of at least out_pubkey_size bytes
 * - out_pubkey_size must be at least 48 bytes
 */

struct FFIResult ffi_dash_spv_get_quorum_public_key(struct FFIDashSpvClient *client,
                                                    uint32_t quorum_type,
                                                    const uint8_t *quorum_hash,
                                                    uint32_t core_chain_locked_height,
                                                    uint8_t *out_pubkey,
                                                    uintptr_t out_pubkey_size)
;

/**
 * Gets the platform activation height from the Core chain
 *
 * # Safety
 *
 * This function is unsafe because:
 * - The caller must ensure all pointers are valid
 * - out_height must point to a valid u32
 */

struct FFIResult ffi_dash_spv_get_platform_activation_height(struct FFIDashSpvClient *client,
                                                             uint32_t *out_height)
;

/**
 * Destroy an `FFIBlockHeadersProgress` object.
 *
 * # Safety
 * - `progress` must be a pointer returned from this crate, or null.
 */
 void dash_spv_ffi_block_headers_progress_destroy(struct FFIBlockHeadersProgress *progress) ;

/**
 * Destroy an `FFIFilterHeadersProgress` object.
 *
 * # Safety
 * - `progress` must be a pointer returned from this crate, or null.
 */
 void dash_spv_ffi_filter_headers_progress_destroy(struct FFIFilterHeadersProgress *progress) ;

/**
 * Destroy an `FFIFiltersProgress` object.
 *
 * # Safety
 * - `progress` must be a pointer returned from this crate, or null.
 */
 void dash_spv_ffi_filters_progress_destroy(struct FFIFiltersProgress *progress) ;

/**
 * Destroy an `FFIBlocksProgress` object.
 *
 * # Safety
 * - `progress` must be a pointer returned from this crate, or null.
 */
 void dash_spv_ffi_blocks_progress_destroy(struct FFIBlocksProgress *progress) ;

/**
 * Destroy an `FFIMasternodesProgress` object.
 *
 * # Safety
 * - `progress` must be a pointer returned from this crate, or null.
 */
 void dash_spv_ffi_masternode_progress_destroy(struct FFIMasternodesProgress *progress) ;

/**
 * Destroy an `FFIChainLockProgress` object.
 *
 * # Safety
 * - `progress` must be a pointer returned from this crate, or null.
 */
 void dash_spv_ffi_chainlock_progress_destroy(struct FFIChainLockProgress *progress) ;

/**
 * Destroy an `FFIInstantSendProgress` object.
 *
 * # Safety
 * - `progress` must be a pointer returned from this crate, or null.
 */
 void dash_spv_ffi_instantsend_progress_destroy(struct FFIInstantSendProgress *progress) ;

/**
 * Destroy an `FFISyncProgress` object and all its nested pointers.
 *
 * # Safety
 * - `progress` must be a pointer returned from this crate, or null.
 */
 void dash_spv_ffi_manager_sync_progress_destroy(struct FFISyncProgress *progress) ;

/**
 * Initialize logging for the SPV library.
 *
 * # Arguments
 * - `level`: Log level string (null uses RUST_LOG env var or defaults to INFO).
 *   Valid values: "error", "warn", "info", "debug", "trace"
 * - `enable_console`: Whether to output logs to console (stderr)
 * - `log_dir`: Directory for log files (null to disable file logging)
 * - `max_files`: Maximum archived log files to retain (ignored if log_dir is null)
 *
 * # Safety
 * - `level` and `log_dir` may be null or point to valid, NUL-terminated C strings.
 */

int32_t dash_spv_ffi_init_logging(const char *level,
                                  bool enable_console,
                                  const char *log_dir,
                                  uintptr_t max_files)
;

 const char *dash_spv_ffi_version(void) ;

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace dash_spv_ffi
#endif  // __cplusplus

#endif  /* DASH_SPV_FFI_H */
