#!/usr/bin/env bash

set -e

REPO_DIR=$(git rev-parse --show-toplevel)

# shellcheck source=./fuzz-util.sh
source "$REPO_DIR/fuzz/fuzz-util.sh"

# 1. Generate fuzz/Cargo.toml
cat > "$REPO_DIR/fuzz/Cargo.toml" <<EOF
[package]
name = "dash-fuzz"
edition = "2024"
version = { workspace = true }
authors = ["Generated by fuzz/generate-files.sh"]
license = "CC0-1.0"
publish = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fuzzing)"] }

[package.metadata]
cargo-fuzz = true

[dependencies]
honggfuzz = { version = "0.5", default-features = false }
dashcore = { path = "../dash", features = [ "serde" ] }
key-wallet = { path = "../key-wallet" }

serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0"
serde_cbor = "0.11"
EOF

for targetFile in $(listAllTargetFiles); do
    targetName=$(targetFileToName "$targetFile")
    cat >> "$REPO_DIR/fuzz/Cargo.toml" <<EOF

[[bin]]
name = "$targetName"
path = "$targetFile"
EOF
done
